priority:
  - title:
    - EIC-Book/EIC-AV
  - poster:
    - EIC-Book/EIC-AV
  - actors:
    - EIC-Book/EIC-AV
  - movie_format:
    - EIC-Book/EIC-AV
  - release_date:
    - EIC-Book/EIC-AV
  - maker:
    - EIC-Book/EIC-AV
  - set:
    - EIC-Book/EIC-AV
  - plot:
    - EIC-Book/EIC-AV