version: '{branch}-{build}'

build: off

environment:
  matrix:
    - TOXENV: 'py36'
    - TOXENV: "py37"
    - TOXENV: "py38"

install:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  - python --version
  - python -m pip install --upgrade pip setuptools wheel
  - pip --version
  - pip install tox

test_script:
  - tox -e %TOXENV%"
